export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_SCHEDULE = 'SET_SCHEDULE';
export const START_FETCH_USER_BY_TOKEN = 'START_FETCH_USER_BY_TOKEN';
export const SUCCESS_FETCH_USER_BY_TOKEN = 'SUCCESS_FETCH_USER_BY_TOKEN';
export const ERROR_FETCH_USER_BY_TOKEN = 'ERROR_FETCH_USER_BY_TOKEN';
