export const START_FETCHING_MY_BOOKING = 'START_FETCHING_MY_BOOKING';
export const SUCCESS_FETCHING_MY_BOOKING = 'SUCCESS_FETCHING_MY_BOOKING';
export const ERROR_FETCHING_MY_BOOKING = 'ERROR_FETCHING_MY_BOOKING';
