export const START_FETCHING_MY_BOOKING = 'START_FETCHING_MY_BOOKING';
export const SUCCESS_FETCHING_MY_BOOKING = 'SUCCESS_FETCHING_MY_BOOKING';
export const ERROR_FETCHING_MY_BOOKING = 'ERROR_FETCHING_MY_BOOKING';
export const START_MAKING_A_BOOKING = 'START_MAKING_A_BOOKING';
export const SUCCESS_MAKING_A_BOOKING = 'SUCCESS_MAKING_A_BOOKING';
export const ERROR_MAKING_A_BOOKING = 'ERROR_MAKING_A_BOOKING';
export const CLEAR_REDIRECT = 'CLEAR_REDIRECT';
