export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const INCREASE_FETCHED_DATA_COUNT = 'INCREASE_FETCHED_DATA_COUNT';
export const INCREASE_SELECTED_INDEX = 'INCREASE_SELECTED_INDEX';
export const DECREASE_SELECTED_INDEX = 'DECREASE_SELECTED_INDEX';
export const START_FETCHING_TEACHERS = 'START_FETCHING_TEACHERS';
